spring.application.name=projetoGerenciamento
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://143.106.241.4:3306/cl204462
spring.datasource.username=cl204462
spring.datasource.password=cl*01092008
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true