spring.datasource.url=jdbc:postgresql://ep-dawn-mud-80362511-pooler.us-east-2.aws.neon.tech:5432/cookie_hub?sslmode=require
spring.datasource.username=rbertho
spring.datasource.password=3hi2PaNMcgUS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret=dGhpcytpc215c2VjcmV0a2V5Zm9yand0dG9rZW5nZW5lcmF0aW9u